import { appUrl } from "@/lib/email";

const ACCENT = "#ec3013";
const INK = "#1a1a1a";
const PAPER = "#f3f2f2";

function shell(title: string, body: string): string {
  return `<!doctype html>
<html>
  <body style="margin:0;padding:24px;background:${PAPER};font-family:Archivo,Arial,Helvetica,sans-serif;color:${INK};">
    <div style="max-width:560px;margin:0 auto;background:#ffffff;border:2px solid ${INK};">
      <div style="border-bottom:2px solid ${INK};padding:16px 20px;">
        <span style="display:block;font-size:12px;letter-spacing:1px;text-transform:uppercase;color:${ACCENT};font-weight:700;">Asana Ortho</span>
        <span style="display:block;font-size:18px;font-weight:700;">${title}</span>
      </div>
      <div style="padding:20px;font-size:14px;line-height:1.55;">
        ${body}
      </div>
    </div>
  </body>
</html>`;
}

function fmtDate(d: Date): string {
  return d.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
}

function fmtMoney(n: number): string {
  return n.toLocaleString("en-US", { style: "currency", currency: "USD" });
}

export interface PurchaseOrderEmailInput {
  poNumber: string;
  vendorName: string;
  productName: string;
  qty: number;
  unitPrice: number;
  deliveryDays: number;
  dueDate: Date;
  orderedBy: string;
}

export function purchaseOrderEmail(input: PurchaseOrderEmailInput) {
  const lineTotal = input.unitPrice * input.qty;
  const subject = `Purchase Order ${input.poNumber} — ${input.qty} × ${input.productName}`;
  const text = [
    `Purchase Order ${input.poNumber}`,
    `Vendor: ${input.vendorName}`,
    `Product: ${input.productName}`,
    `Quantity: ${input.qty}`,
    `Unit price: ${fmtMoney(input.unitPrice)}`,
    `Order total: ${fmtMoney(lineTotal)}`,
    `Expected delivery: ${input.deliveryDays} day(s) — due ${fmtDate(input.dueDate)}`,
    `Ordered by: ${input.orderedBy}`,
  ].join("\n");

  const html = shell(
    "Purchase Order",
    `<p style="margin:0 0 12px;">Please supply the following order for Asana Ortho.</p>
     <table style="width:100%;border-collapse:collapse;font-size:14px;">
       <tbody>
         ${row("PO Number", input.poNumber)}
         ${row("Product", input.productName)}
         ${row("Quantity", String(input.qty))}
         ${row("Unit price", fmtMoney(input.unitPrice))}
         ${row("Order total", `<strong>${fmtMoney(lineTotal)}</strong>`)}
         ${row("Expected delivery", `${input.deliveryDays} day(s) — due ${fmtDate(input.dueDate)}`)}
         ${row("Ordered by", input.orderedBy)}
       </tbody>
     </table>
     <p style="margin:16px 0 0;color:#6b6b6b;font-size:12px;">This purchase order was generated by the Asana Ortho Inventory Manager.</p>`,
  );

  return { subject, html, text };
}

export interface ReminderEmailInput {
  requestId: string;
  productName: string;
  qty: number;
  dueDate: Date;
  vendorName?: string | null;
  requestedBy: string;
}

export function reminderEmail(input: ReminderEmailInput) {
  const link = `${appUrl()}/admin/awaiting?highlight=${input.requestId}`;
  const subject = `Delivery due: ${input.qty} × ${input.productName} (due ${fmtDate(input.dueDate)})`;
  const text =
    `Order for ${input.qty} × ${input.productName} was due ${fmtDate(input.dueDate)} — ` +
    `please confirm receipt or mark it received in the portal.\n${link}`;

  const html = shell(
    "Delivery Reminder",
    `<p style="margin:0 0 12px;">Order for <strong>${input.qty} × ${input.productName}</strong> was due <strong>${fmtDate(input.dueDate)}</strong>.</p>
     <p style="margin:0 0 16px;">Please confirm receipt or mark it received in the portal.</p>
     ${input.vendorName ? `<p style="margin:0 0 4px;color:#6b6b6b;">Vendor: ${input.vendorName}</p>` : ""}
     <p style="margin:0 0 16px;color:#6b6b6b;">Requested by: ${input.requestedBy}</p>
     <a href="${link}" style="display:inline-block;background:${ACCENT};color:#ffffff;text-decoration:none;padding:10px 16px;font-weight:700;border:2px solid ${INK};">Open in portal</a>`,
  );

  return { subject, html, text };
}

function row(label: string, value: string): string {
  return `<tr>
    <td style="padding:8px 0;border-bottom:1px solid #e2e2e2;color:#6b6b6b;width:40%;">${label}</td>
    <td style="padding:8px 0;border-bottom:1px solid #e2e2e2;text-align:right;">${value}</td>
  </tr>`;
}
